### ISSUE TITLE
Refactor calcDynamics!

### ISSUE THREAD

**Issue by X-N-C** [X-N-C/JitterTime.jl#1]
[calcDynamics!](https://github.com/X-N-C/JitterTime.jl/blob/main/src/JitterTime.jl#L37) is not type stable. Maybe factor out subfunctions would improve performance and readability.

**Comment by NilsVreman** [comment]
Broke out long functions into subfunctions with specific assignments. Also type-specified a few variables that helped the compiler. The solutions should help improve both type-stability and readability!
